//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOPF_DP_QUERY
    {
        public int ID { get; set; }
        public int QUERY { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<decimal> MAPPING_ID { get; set; }
    
        public virtual EOPF_DP_MAPPING EOPF_DP_MAPPING { get; set; }
    }
}
