//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOPF_DP_SETTING
    {
        public decimal ID { get; set; }
        public string SERVICE_URL { get; set; }
        public string SERVICE_KEY { get; set; }
        public string SERVICE_USERNAME { get; set; }
        public string SERVICE_PASSWORD { get; set; }
        public string LOG_PATH { get; set; }
        public string ENVIRONMENT { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
