//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOPF_DP_SUB_MAPPING
    {
        public decimal ID { get; set; }
        public string TABLE_NAME { get; set; }
        public decimal PARENT { get; set; }
    
        public virtual EOPF_DP_MAPPING EOPF_DP_MAPPING { get; set; }
    }
}
