//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOPF_AGENCY_DETAILS
    {
        public decimal EAD_ID { get; set; }
        public Nullable<decimal> EAD_POI_CODE { get; set; }
        public string EAD_CODE { get; set; }
        public string EAD_DESCRIPTION { get; set; }
        public string EAD_CITY { get; set; }
        public string EAD_STATE { get; set; }
        public Nullable<decimal> EAD_EAI_ID { get; set; }
    
        public virtual EOPF_AGENCY_INFO EOPF_AGENCY_INFO { get; set; }
    }
}
